{% set name = "xcube-cds" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-cds/archive/v{{ version }}.tar.gz
  sha256: 635f28b8a5c72354af75dc143d5081dd6da2334ab849ad5687c9a229a05798e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    # Python
    - python >=3.6
    # Required
    - xcube >=0.7.0
    - cdsapi >=0.2.7
    - python-dateutil >=2.8.1
    - xarray
    - numpy >=1.17
    - jsonschema >=3.2.0
test:
  imports:
    - xcube_cds

about:
  summary: xcube plugin for the Climate Data Store (CDS) API
  home: https://github.com/dcs4cop/xcube-cds
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cds is an xcube plugin which can generate data cubes from the Copernicus Climate Data Store (CDS) API.
  doc_url: https://github.com/dcs4cop/xcube-cds/blob/master/README.md
  dev_url: https://github.com/dcs4cop/xcube-cds

extra:
  recipe-maintainers:
    - pont-us
    - dzelge
    - TonioF
    - forman
    - AliceBalfanz
