{% set name = "xcube-cds" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-cds/archive/v{{ version }}.tar.gz
  sha256: 830fc84a0cf74460c339ab6806e3a71cc3bde162b2fbb841ee739adf0d008802

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    # Python
    - python >=3.8
    # Required
    - cdsapi >=0.5.1
    - jsonschema >=3.2.0
    - numpy >=1.17
    - python-dateutil >=2.8.1
    - xarray >=0.18.2
    - xcube >=0.9.0
test:
  imports:
    - xcube_cds

about:
  summary: xcube plugin for the Climate Data Store (CDS) API
  home: https://github.com/dcs4cop/xcube-cds
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cds is an xcube plugin which can generate data cubes from the Copernicus Climate Data Store (CDS) API.
  doc_url: https://github.com/dcs4cop/xcube-cds/blob/master/README.md
  dev_url: https://github.com/dcs4cop/xcube-cds

extra:
  recipe-maintainers:
    - pont-us
    - dzelge
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
